version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: cromometro-postgres
    restart: always
    environment:
      POSTGRES_USER: cromometro
      POSTGRES_PASSWORD: cromometro
      POSTGRES_DB: cromometro
    ports:
      - "5432:5432"
    volumes:
      - cromometro_pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: cromometro-mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  cromometro_pgdata:
